FROM oven/bun:1 AS base

FROM base AS pruner
WORKDIR /app
RUN bun add -g turbo
COPY . .
RUN turbo prune @repo/frontend --docker

FROM base AS installer
WORKDIR /app
COPY --from=pruner /app/out/json/ .
RUN bun install --frozen-lockfile
COPY --from=pruner /app/out/full/ .
RUN bun run turbo build --filter=@repo/frontend

FROM base AS runner
WORKDIR /app
COPY --from=installer /app .

CMD ["bun", "--cwd", "apps/frontend", "start"]