---
apiVersion: v1
kind: Secret
metadata:
  name: port
type: Opaque
stringData:
  PORT: "4000"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt
type: Opaque
stringData:
  JWT_ACCESS_SECRET: your-jwt-access-secret
  JWT_REFRESH_SECRET: your-jwt-refresh-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@host.docker.internal:5432/dbname"
---
apiVersion: v1
kind: Secret
metadata:
  name: google
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: your-google-client-id.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: your-google-client-secret
  GOOGLE_REFRESH_TOKEN: your-google-refresh-token
---
apiVersion: v1
kind: Secret
metadata:
  name: email
type: Opaque
stringData:
  EMAIL_USER: your-email@gmail.com
---
apiVersion: v1
kind: Secret
metadata:
  name: llm
type: Opaque
stringData:
  LLM_PROVIDER: mistral
  MISTRAL_API_KEY: your-mistral-api-key
---
apiVersion: v1
kind: Secret
metadata:
  name: app
type: Opaque
stringData:
  NODE_ENV: development
  FRONTEND_URL: http://localhost:3000
