import Link from "next/link";

export function FinalCta() {
  return (
    <section className="px-6 py-32">
      <div className="relative mx-auto flex max-w-4xl flex-col items-center overflow-hidden rounded-3xl border border-surface-bright bg-surface-container-high p-16 text-center md:p-24">
        <div className="relative z-10">
          <h2 className="mb-8 text-4xl font-extrabold uppercase tracking-tighter text-on-surface md:text-5xl">
            Documentation, Automated
          </h2>
          <p className="mx-auto mb-12 max-w-xl text-lg text-on-surface-variant">
            Point GitFlow at a repository and get structured, readable docs
            with real sequence diagrams — generated by AI, grounded in your
            actual source code.
          </p>
          <Link
            href="/login"
            className="inline-block rounded bg-on-surface px-12 py-5 text-sm font-bold uppercase tracking-wider text-background transition-transform hover:scale-105 hover:bg-primary"
          >
            Get started free
          </Link>
        </div>
      </div>
    </section>
  );
}